require 'general/settings'
require 'keys/mappings'

require 'plug-config/plugins'
require 'plug-config/airline'
require 'plug-config/coc'
require 'plug-config/gruvbox-material'
require 'plug-config/hexokinase'
require 'plug-config/rnvimr'
require 'plug-config/sneak'
require 'plug-config/supertab'
require 'plug-config/ultisnips'
-- require 'plug-config/vim-pandoc'
require 'plug-config/vimtex'
require 'plug-config/lspconfig'
require 'plug-config/cmp'
-- require 'plug-config/neorg'
